/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author varga
 */
public class VentanaTeclado extends javax.swing.JFrame {

    /**
     * Creates new form VentanaTeclado
     */
    public VentanaTeclado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox29 = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        cbϿ = new javax.swing.JCheckBox();
        cbWStar = new javax.swing.JCheckBox();
        cbDStar = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cbThous = new javax.swing.JCheckBox();
        cbϘ = new javax.swing.JCheckBox();
        cbѢ = new javax.swing.JCheckBox();
        cbѦ = new javax.swing.JCheckBox();
        cbѬ = new javax.swing.JCheckBox();
        cbæ = new javax.swing.JCheckBox();
        cbҖ = new javax.swing.JCheckBox();
        cbCopy = new javax.swing.JCheckBox();
        lbOrden = new javax.swing.JLabel();
        cbӬ = new javax.swing.JCheckBox();
        btnOrdenar = new javax.swing.JButton();
        cbҨ = new javax.swing.JCheckBox();
        cbѼ = new javax.swing.JCheckBox();
        cbҊ = new javax.swing.JCheckBox();
        cbϗ = new javax.swing.JCheckBox();
        cbټ = new javax.swing.JCheckBox();
        cbϰ = new javax.swing.JCheckBox();
        cbԆ = new javax.swing.JCheckBox();
        cbQuer = new javax.swing.JCheckBox();
        cbψ = new javax.swing.JCheckBox();
        cbΩ = new javax.swing.JCheckBox();
        cbPilc = new javax.swing.JCheckBox();
        cbƛ = new javax.swing.JCheckBox();
        cbѮ = new javax.swing.JCheckBox();
        cbϬ = new javax.swing.JCheckBox();
        cbϾ = new javax.swing.JCheckBox();

        jCheckBox14.setText("jCheckBox10");

        jCheckBox15.setText("jCheckBox10");

        jLabel2.setText("jLabel2");

        jCheckBox29.setText("jCheckBox29");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        cbϿ.setBackground(new java.awt.Color(0, 0, 0));
        cbϿ.setForeground(new java.awt.Color(255, 255, 255));
        cbϿ.setText("Ͽ");

        cbWStar.setBackground(new java.awt.Color(0, 0, 0));
        cbWStar.setForeground(new java.awt.Color(255, 255, 255));
        cbWStar.setText("☆");

        cbDStar.setBackground(new java.awt.Color(0, 0, 0));
        cbDStar.setForeground(new java.awt.Color(255, 255, 255));
        cbDStar.setText("★");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TECLADO:");

        cbThous.setBackground(new java.awt.Color(0, 0, 0));
        cbThous.setForeground(new java.awt.Color(255, 255, 255));
        cbThous.setText("҂");

        cbϘ.setBackground(new java.awt.Color(0, 0, 0));
        cbϘ.setForeground(new java.awt.Color(255, 255, 255));
        cbϘ.setText("Ϙ");

        cbѢ.setBackground(new java.awt.Color(0, 0, 0));
        cbѢ.setForeground(new java.awt.Color(255, 255, 255));
        cbѢ.setText("Ѣ");

        cbѦ.setBackground(new java.awt.Color(0, 0, 0));
        cbѦ.setForeground(new java.awt.Color(255, 255, 255));
        cbѦ.setText("Ѧ");

        cbѬ.setBackground(new java.awt.Color(0, 0, 0));
        cbѬ.setForeground(new java.awt.Color(255, 255, 255));
        cbѬ.setText("Ѭ");

        cbæ.setBackground(new java.awt.Color(0, 0, 0));
        cbæ.setForeground(new java.awt.Color(255, 255, 255));
        cbæ.setText("æ");

        cbҖ.setBackground(new java.awt.Color(0, 0, 0));
        cbҖ.setForeground(new java.awt.Color(255, 255, 255));
        cbҖ.setText("Җ");

        cbCopy.setBackground(new java.awt.Color(0, 0, 0));
        cbCopy.setForeground(new java.awt.Color(255, 255, 255));
        cbCopy.setText("©");

        lbOrden.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lbOrden.setForeground(new java.awt.Color(255, 255, 255));
        lbOrden.setText("Orden:");

        cbӬ.setBackground(new java.awt.Color(0, 0, 0));
        cbӬ.setForeground(new java.awt.Color(255, 255, 255));
        cbӬ.setText("Ӭ");

        btnOrdenar.setForeground(new java.awt.Color(0, 0, 0));
        btnOrdenar.setText("ORDENAR:");

        cbҨ.setBackground(new java.awt.Color(0, 0, 0));
        cbҨ.setForeground(new java.awt.Color(255, 255, 255));
        cbҨ.setText("Ҩ");

        cbѼ.setBackground(new java.awt.Color(0, 0, 0));
        cbѼ.setForeground(new java.awt.Color(255, 255, 255));
        cbѼ.setText("Ѽ");

        cbҊ.setBackground(new java.awt.Color(0, 0, 0));
        cbҊ.setForeground(new java.awt.Color(255, 255, 255));
        cbҊ.setText("Ҋ");

        cbϗ.setBackground(new java.awt.Color(0, 0, 0));
        cbϗ.setForeground(new java.awt.Color(255, 255, 255));
        cbϗ.setText("ϗ");

        cbټ.setBackground(new java.awt.Color(0, 0, 0));
        cbټ.setForeground(new java.awt.Color(255, 255, 255));
        cbټ.setText("ټ");

        cbϰ.setBackground(new java.awt.Color(0, 0, 0));
        cbϰ.setForeground(new java.awt.Color(255, 255, 255));
        cbϰ.setText("ϰ");

        cbԆ.setBackground(new java.awt.Color(0, 0, 0));
        cbԆ.setForeground(new java.awt.Color(255, 255, 255));
        cbԆ.setText("Ԇ");

        cbQuer.setBackground(new java.awt.Color(0, 0, 0));
        cbQuer.setForeground(new java.awt.Color(255, 255, 255));
        cbQuer.setText("¿");

        cbψ.setBackground(new java.awt.Color(0, 0, 0));
        cbψ.setForeground(new java.awt.Color(255, 255, 255));
        cbψ.setText("ψ");

        cbΩ.setBackground(new java.awt.Color(0, 0, 0));
        cbΩ.setForeground(new java.awt.Color(255, 255, 255));
        cbΩ.setText("Ω");

        cbPilc.setBackground(new java.awt.Color(0, 0, 0));
        cbPilc.setForeground(new java.awt.Color(255, 255, 255));
        cbPilc.setText("¶");

        cbƛ.setBackground(new java.awt.Color(0, 0, 0));
        cbƛ.setForeground(new java.awt.Color(255, 255, 255));
        cbƛ.setText("ƛ");

        cbѮ.setBackground(new java.awt.Color(0, 0, 0));
        cbѮ.setForeground(new java.awt.Color(255, 255, 255));
        cbѮ.setText("Ѯ");

        cbϬ.setBackground(new java.awt.Color(0, 0, 0));
        cbϬ.setForeground(new java.awt.Color(255, 255, 255));
        cbϬ.setText("Ϭ");

        cbϾ.setBackground(new java.awt.Color(0, 0, 0));
        cbϾ.setForeground(new java.awt.Color(255, 255, 255));
        cbϾ.setText("Ͼ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(cbæ)
                            .addComponent(cbCopy)
                            .addComponent(cbӬ)
                            .addComponent(cbҨ)
                            .addComponent(cbҊ)
                            .addComponent(cbϗ)
                            .addComponent(cbϰ)
                            .addComponent(cbԆ)
                            .addComponent(cbϘ))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbѮ)
                            .addComponent(cbΩ)
                            .addComponent(cbQuer)
                            .addComponent(cbƛ)
                            .addComponent(cbϬ)
                            .addComponent(cbψ)
                            .addComponent(cbPilc)
                            .addComponent(cbϾ)
                            .addComponent(cbϿ))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbWStar)
                            .addComponent(cbDStar)
                            .addComponent(cbټ)
                            .addComponent(cbѼ)
                            .addComponent(cbҖ)
                            .addComponent(cbѦ)
                            .addComponent(cbѬ)
                            .addComponent(cbThous)
                            .addComponent(cbѢ)))
                    .addComponent(btnOrdenar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lbOrden))
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbæ)
                    .addComponent(cbѮ)
                    .addComponent(cbѢ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCopy)
                    .addComponent(cbΩ)
                    .addComponent(cbThous, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbӬ)
                    .addComponent(cbQuer)
                    .addComponent(cbѬ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbҨ)
                    .addComponent(cbƛ)
                    .addComponent(cbѦ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbҊ)
                    .addComponent(cbϬ)
                    .addComponent(cbҖ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbϗ)
                    .addComponent(cbψ)
                    .addComponent(cbѼ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbϰ)
                    .addComponent(cbPilc)
                    .addComponent(cbټ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbԆ)
                    .addComponent(cbϾ)
                    .addComponent(cbDStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbϘ)
                    .addComponent(cbϿ)
                    .addComponent(cbWStar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnOrdenar)
                .addGap(18, 18, 18)
                .addComponent(lbOrden)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTeclado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTeclado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnOrdenar;
    public javax.swing.JCheckBox cbCopy;
    public javax.swing.JCheckBox cbDStar;
    public javax.swing.JCheckBox cbPilc;
    public javax.swing.JCheckBox cbQuer;
    public javax.swing.JCheckBox cbThous;
    public javax.swing.JCheckBox cbWStar;
    public javax.swing.JCheckBox cbæ;
    public javax.swing.JCheckBox cbƛ;
    public javax.swing.JCheckBox cbΩ;
    public javax.swing.JCheckBox cbψ;
    public javax.swing.JCheckBox cbϗ;
    public javax.swing.JCheckBox cbϘ;
    public javax.swing.JCheckBox cbϬ;
    public javax.swing.JCheckBox cbϰ;
    public javax.swing.JCheckBox cbϾ;
    public javax.swing.JCheckBox cbϿ;
    public javax.swing.JCheckBox cbѢ;
    public javax.swing.JCheckBox cbѦ;
    public javax.swing.JCheckBox cbѬ;
    public javax.swing.JCheckBox cbѮ;
    public javax.swing.JCheckBox cbѼ;
    public javax.swing.JCheckBox cbҊ;
    public javax.swing.JCheckBox cbҖ;
    public javax.swing.JCheckBox cbҨ;
    public javax.swing.JCheckBox cbӬ;
    public javax.swing.JCheckBox cbԆ;
    public javax.swing.JCheckBox cbټ;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lbOrden;
    // End of variables declaration//GEN-END:variables
}
